show tables;

describe login_master_files.person_TBL;
describe login_master_files.company_TBL;

describe company_schema_example.member_TBL;
describe company_schema_example.job_TBL;
describe company_schema_example.job_time_log_TBL;
describe company_schema_example.communication_TBL;
describe company_schema_example.client_company_TBL;
describe company_schema_example.address_TBL;
describe company_schema_example.client_com_link_jobs_TBL;
