-- MySQL Script generated by MySQL Workbench
-- Fri 01 Jan 2016 17:31:45 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema fayino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fayino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fayino` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `fayino` ;

-- -----------------------------------------------------
-- Table `fayino`.`address_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`address_TBL` (
  `addressID` INT(11) NOT NULL,
  `addressLine1` VARCHAR(45) NULL DEFAULT NULL,
  `addressLine2` VARCHAR(45) NULL DEFAULT NULL,
  `addressTown` VARCHAR(45) NULL DEFAULT NULL,
  `addressCounty` VARCHAR(45) NULL DEFAULT NULL,
  `addressCountry` VARCHAR(45) NULL DEFAULT NULL,
  `addressPostcode` VARCHAR(45) NULL DEFAULT NULL,
  `addressType` VARCHAR(45) NULL DEFAULT NULL,
  `Default` TINYINT(1) NULL DEFAULT NULL,
  `personID` INT(11) NULL DEFAULT NULL,
  `companyID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`addressID`),
  UNIQUE INDEX `addressID_UNIQUE` (`addressID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`company_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`company_TBL` (
  `companyID` INT(11) NOT NULL,
  `companyName` VARCHAR(100) NOT NULL,
  `companyCode` VARCHAR(8) NOT NULL,
  `companyDesc` VARCHAR(1000) NULL DEFAULT NULL,
  `companyType` VARCHAR(45) NULL DEFAULT NULL,
  `companyOwer` INT(11) NULL DEFAULT NULL,
  `companyAdmin` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`companyID`),
  UNIQUE INDEX `companyID_UNIQUE` (`companyID` ASC),
  UNIQUE INDEX `companyCode_UNIQUE` (`companyCode` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`email_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`email_TBL` (
  `emailID` INT(11) NOT NULL,
  `emailAddress` VARCHAR(150) NOT NULL,
  `emailType` VARCHAR(45) NULL DEFAULT NULL,
  `Default` TINYINT(1) NULL DEFAULT NULL,
  `personID` INT(11) NULL DEFAULT NULL,
  `companyID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`emailID`),
  UNIQUE INDEX `emailID_UNIQUE` (`emailID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`person_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`person_TBL` (
  `personID` INT(11) NOT NULL,
  `fName` VARCHAR(45) NULL DEFAULT NULL,
  `lName` VARCHAR(45) NULL DEFAULT NULL,
  `userName` VARCHAR(100) NULL DEFAULT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `personType` VARCHAR(45) NULL DEFAULT NULL,
  `joinDate` DATE NULL DEFAULT NULL,
  `acceptTErms` DATE NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `loginEmail` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`personID`),
  UNIQUE INDEX `personID_UNIQUE` (`personID` ASC),
  UNIQUE INDEX `loginEmail_UNIQUE` (`loginEmail` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`employee_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`employee_TBL` (
  `personID` INT(11) NOT NULL,
  `companyID` INT(11) NOT NULL,
  PRIMARY KEY (`personID`, `companyID`),
  INDEX `com_FK` (`companyID` ASC),
  CONSTRAINT `com_FK`
    FOREIGN KEY (`companyID`)
    REFERENCES `fayino`.`company_TBL` (`companyID`),
  CONSTRAINT `per_FK`
    FOREIGN KEY (`personID`)
    REFERENCES `fayino`.`person_TBL` (`personID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`job_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`job_TBL` (
  `jobIDyear` INT(4) NOT NULL,
  `jobIDnum` INT(6) NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `entryDate` DATE NOT NULL,
  `pTime` INT(11) NULL DEFAULT NULL,
  `pCost` FLOAT(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`jobIDyear`, `jobIDnum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`job_time_log_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`job_time_log_TBL` (
  `job_time_log_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `jobIDyear` INT(4) NOT NULL,
  `jobIDnum` INT(6) NOT NULL,
  `personID` INT(11) NOT NULL,
  `startTime` DATETIME NOT NULL,
  `finishTime` DATETIME NULL DEFAULT NULL,
  `totalTime` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`job_time_log_ID`),
  INDEX `per_job_FK` (`personID` ASC),
  INDEX `job_time_FK` (`jobIDyear` ASC, `jobIDnum` ASC),
  CONSTRAINT `job_time_FK`
    FOREIGN KEY (`jobIDyear` , `jobIDnum`)
    REFERENCES `fayino`.`job_TBL` (`jobIDyear` , `jobIDnum`),
  CONSTRAINT `per_job_FK`
    FOREIGN KEY (`personID`)
    REFERENCES `fayino`.`person_TBL` (`personID`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fayino`.`phone_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`phone_TBL` (
  `phoneID` INT(11) NOT NULL,
  `phoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  `phoneType` VARCHAR(45) NULL DEFAULT NULL,
  `default` TINYINT(1) NULL DEFAULT NULL,
  `personID` INT(11) NULL DEFAULT NULL,
  `companyID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`phoneID`),
  UNIQUE INDEX `phoneID_UNIQUE` (`phoneID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
