-- MySQL Script generated by MySQL Workbench
-- Mon 23 Nov 2015 21:51:59 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fayino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fayino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fayino` DEFAULT CHARACTER SET utf8 ;
USE `fayino` ;

-- -----------------------------------------------------
-- Table `fayino`.`company_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`company_TBL` (
  `companyID` INT NOT NULL,
  `companyName` VARCHAR(100) NOT NULL,
  `companyEmail` VARCHAR(100) NULL,
  `joinDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `companyTag` VARCHAR(6) NULL,
  PRIMARY KEY (`companyID`),
  UNIQUE INDEX `idcompany_TBL_UNIQUE` (`companyID` ASC),
  UNIQUE INDEX `companyTag_UNIQUE` (`companyTag` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fayino`.`user_TBL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fayino`.`user_TBL` (
  `iduser_TBL` INT NOT NULL,
  `userName` VARCHAR(45) NULL,
  `userEmail` VARCHAR(50) NULL,
  `userPassword` VARCHAR(45) NULL,
  `companyID` INT NULL,
  `joinDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser_TBL`),
  UNIQUE INDEX `iduser_TBL_UNIQUE` (`iduser_TBL` ASC),
  INDEX `fk_user_TBL_company_TBL_idx` (`companyID` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  CONSTRAINT `fk_user_TBL_company_TBL`
    FOREIGN KEY (`companyID`)
    REFERENCES `fayino`.`company_TBL` (`companyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
